swagger: "2.0"
info:
  version: "1.0.0"
  title: 'CQUBE'

basePath: "/v0"

tags:
  - name: "spec"
  - name: "ingestion"

schemes:
  - "https"
  - "http"

paths:
  /spec/event:
    post:
      tags:
        - "spec"
      summary: "Create a new event Specification"
      description: "Add new event Specification"
      operationId: "eventSpecification"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              event_name:
                type: "string"
                example: "student_count"
              dimensions:
                description: "The dimensions Schema"
                type: "array"
                items:
                  type: "object"
                  properties:
                    id:
                      type: "string"
                      example: "D1"
                    key:
                      type: "string"
                      example: "schoolId"
              items:
                description: "The items Schema"
                type: "object"
                properties:
                 schoolId:
                   type: "string"
                   example: "number"
                 grade:
                   type: "string"
                   example: "number"
                 count:
                  type: "string"
                  example: "number"
      responses:
        200:
          description: "Event Spec Created Successfully"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Event Spec Created Successfully"
              pid:
                type: "integer"
                example: 1
              event_name:
                type: "string"
                example: "student_count"
        400:
          description: "Something went wrong"
          schema:
            $ref: "#/definitions/generic_error"
  /spec/dimension:
    post:
      tags:
        - "spec"
      summary: "Create a new dimension Specification"
      description: "Add new dimension Specification"
      operationId: "dimensionSpecification"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              dimension_name:
                type: "string"
                example: "district"
              dimension:
                  type: "object"
                  properties:
                    schoolId:
                      type: "string"
                    district:
                      type: "string"
                    block:
                      type: "string"
      responses:
        200:
          description: "Dimension Spec Created Successfully"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Dimension Spec Created Successfully"
              pid:
                type: "integer"
                example: 4
              dimension_name:
                type: "string"
                example: "district"
        400:
          description: "Something went wrong"
          schema:
            $ref: "#/definitions/generic_error"
  /spec/dataset:
    post:
      tags:
        - "spec"
      summary: "Create a new dataset Specification"
      description: "Add new dataset Specification"
      operationId: "datasetSpecification"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              dataset_name:
                type: "string"
                example: "student_count_by_school_and_grade"
              dataset:
                  type: "object"
                  properties:
                    dimensions:
                      type: "object"
                      properties:
                       table:
                        type: "string"
                        example: "ingestion.Dimentions"
                       column:
                        example: ["school_id","school_name"]
                       merge_on_col:
                        type: "string"
                        example: "school_id"
                    items:
                      description: "The items Schema"
                      type: "object"
                      properties:
                       schoolId:
                         type: "string"
                         example: "number"
                       grade:
                         type: "string"
                         example: "number"
                       count:
                        type: "string"
                        example: "number"
                    group_by:
                      example: ["school_id","grade"]
                    aggregates:
                      type: "object"
                      properties:
                        function:
                          example: ["sum"]
                        target_table:
                          type: "string"
                          example: "ingestion.student_count_by_school_and_grade"
                        columns:
                          example: ["count"]

      responses:
        200:
          description: "Dataset Spec Created Successfully"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Dataset Spec Created Successfully"
              pid:
                type: "integer"
                example: 3
              dataset_name:
                type: "string"
                example: "student_count"
        400:
          description: "Something went wrong"
          schema:
            $ref: "#/definitions/generic_error"
  /spec/transformer:
    post:
      tags:
        - "spec"
      summary: "Create a new transformer Specification"
      description: "Add new transformer Specification"
      operationId: "transformerSpecification"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              transformer_name:
                type: "string"
                example: "student_count_sum_transformer"
              event_name:
                type: "string"
                example: "student_count"
              dataset_name:
                type: "string"
                example: "student_count"
              template:
                type: "string"
                example: "sum_template"
              function:
                type: "string"
                example: "sum"
      responses:
        200:
          description: "Transformer Spec Created Successfully"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Transformer Spec Created Successfully"
              pid:
                type: "integer"
                example: 5
              file:
                type: "string"
                example: "student_count.py"
        400:
          description: "Something went wrong"
          schema:
            $ref: "#/definitions/generic_error"
  /spec/pipeline:
    post:
      tags:
        - "spec"
      summary: "Create a new pipeline Specification"
      description: "Add new pipeline Specification"
      operationId: "pipelineSpecification"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              pipeline_name:
                type: "string"
                example: "student_count_pipe"
              pipeline:
                type: "array"
                items:
                  type: "object"
                  properties:
                    event_name:
                      type: "string"
                      example: "student_count"
                    dataset_name:
                      type: "string"
                      example: "student_count_by_school_and_grade"
                    dimension_name:
                      type: "string"
                      example: "district"
                    transformer_name:
                      type: "string"
                      example: "student_count_sum_transformer"

      responses:
        200:
          description: "Pipe Spec Created Successfully"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Pipe Spec Created Successfully"
              pid:
                type: "integer"
                example: 2

        400:
          description: "Something went wrong"
          schema:
            $ref: "#/definitions/generic_error"
  /spec/schedule:
    post:
      tags:
        - "spec"
      summary: "create a Schedule"
      description: "Create a schedule"
      operationId: "createSchedule"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              pipeline_name:
                type: "string"
                example: "student_count_pipe"
              schedule_type:
                type: "string"
                example: "dimension_to_db/ingest_to_aggregate/aggregate_to_dataset"
              scheduled_at:
                type: "string"
                example: "12/12/2022 14:00:00"

      responses:
        200:
          description: "Schedule created Successfully"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Schedule created Successfully"
        400:
          description: "Something went wrong"
          schema:
            $ref: "#/definitions/generic_error"


  /ingestion/event:
    post:
      tags:
        - "ingestion"
      summary: "Add Event into a CSV"
      description: "Add event"
      operationId: "addEvent"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              event_name:
                type: "string"
                example: "student_count"
              event:
                type: "object"
                properties:
                  school_id:
                    type: "string"
                    example: "101"
                  grade:
                    type: "string"
                    example: "1"
                  count:
                    type: "string"
                    example: "10"
      responses:
        200:
          description: "Event Added Successfully"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Event Added Successfully"
        400:
          description: "Something went wrong"
          schema:
            $ref: "#/definitions/generic_error"
  /ingestion/dimension:
    post:
      tags:
        - "ingestion"
      summary: "Add dimension into CSV"
      description: "Add dimension"
      operationId: "addDimension"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              dimension_name:
                type: "string"
                example: "district"
              name:
                type: "string"
                example: "Shimla"
              district_id:
                type: "string"
                example: "SH123"
      responses:
        200:
          description: "Dimension Added Successfully"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Dimension Added Successfully"
        400:
          description: "Something went wrong"
          schema:
            $ref: "#/definitions/generic_error"
  /ingestion/dataset:
    post:
      tags:
        - "ingestion"
      summary: "Add dataset"
      description: "Add dataset"
      operationId: "addDataset"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              dataset_name:
                type: "string"
                example: "student_count_by_school_and_grade"
              event_name:
                type: "string"
                example: "student_count"
              dimension_name:
                type: "string"
                example: "District"
      responses:
        200:
          description: "Dataset Added Successfully"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Dataset Added Successfully"
        400:
          description: "Something went wrong"
          schema:
            $ref: "#/definitions/generic_error"
  /ingestion/pipeline:
    post:
      tags:
        - "ingestion"
      summary: "Trigger the pipeline"
      description: "Trigger the pipeline"
      operationId: "triggerPipeline"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              pipeline_name:
                type: "string"
                example: "student_count_pipe"
              type:
                type: "string"
                example: "dimension_to_db/ingest_to_aggregate/aggregate_to_dataset"
      responses:
        200:
          description: "Pipeline Triggered Successfully"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Pipeline Triggered Successfully"
        400:
          description: "Something went wrong"
          schema:
            $ref: "#/definitions/generic_error"

definitions:
  generic_error:
      type: "object"
      properties:
        message:
          type: "string"
          example: "Invalid Input"